--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/MXJosueDev/ComboFly
build-by-default: true
branches:
- devlopment
projects:
  ComboFly:
    path: ""
    icon: "https://raw.githubusercontent.com/MXJosueDev/ComboFly/main/assets/icon.png"
...
